# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'katana_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QFileDialog
from os.path import expanduser
home = expanduser("~")
global home

class MainUI(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(615, 455)
        self.select_multiple_image = QtWidgets.QPushButton(Form)
        self.select_multiple_image.setGeometry(QtCore.QRect(230, 30, 250, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_multiple_image.sizePolicy().hasHeightForWidth())
        self.select_multiple_image.setSizePolicy(sizePolicy)
        self.select_multiple_image.setMinimumSize(QtCore.QSize(0, 0))
        self.select_multiple_image.setIconSize(QtCore.QSize(16, 16))
        self.select_multiple_image.setObjectName("select_multiple_image")
        self.col_label = QtWidgets.QLabel(Form)
        self.col_label.setGeometry(QtCore.QRect(60, 90, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setBold(True)
        font.setWeight(75)
        self.col_label.setFont(font)
        self.col_label.setObjectName("col_label")
        self.nrm_label = QtWidgets.QLabel(Form)
        self.nrm_label.setGeometry(QtCore.QRect(60, 130, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setBold(True)
        font.setWeight(75)
        self.nrm_label.setFont(font)
        self.nrm_label.setObjectName("nrm_label")
        self.rgh_label = QtWidgets.QLabel(Form)
        self.rgh_label.setGeometry(QtCore.QRect(50, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setBold(True)
        font.setWeight(75)
        self.rgh_label.setFont(font)
        self.rgh_label.setObjectName("rgh_label")
        self.met_label = QtWidgets.QLabel(Form)
        self.met_label.setGeometry(QtCore.QRect(50, 210, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setBold(True)
        font.setWeight(75)
        self.met_label.setFont(font)
        self.met_label.setObjectName("met_label")
        self.ao_label = QtWidgets.QLabel(Form)
        self.ao_label.setGeometry(QtCore.QRect(20, 250, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setBold(True)
        font.setWeight(75)
        self.ao_label.setFont(font)
        self.ao_label.setObjectName("ao_label")
        self.emi_label = QtWidgets.QLabel(Form)
        self.emi_label.setGeometry(QtCore.QRect(50, 330, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setBold(True)
        font.setWeight(75)
        self.emi_label.setFont(font)
        self.emi_label.setObjectName("emi_label")
        self.bmp_label = QtWidgets.QLabel(Form)
        self.bmp_label.setGeometry(QtCore.QRect(60, 290, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setBold(True)
        font.setWeight(75)
        self.bmp_label.setFont(font)
        self.bmp_label.setObjectName("bmp_label")
        self.ao_lineEdit = QtWidgets.QLineEdit(Form)
        self.ao_lineEdit.setGeometry(QtCore.QRect(180, 250, 351, 31))
        self.ao_lineEdit.setObjectName("ao_lineEdit")
        self.col_lineEdit = QtWidgets.QLineEdit(Form)
        self.col_lineEdit.setGeometry(QtCore.QRect(180, 90, 351, 31))
        self.col_lineEdit.setObjectName("col_lineEdit")
        self.nrm_lineEdit = QtWidgets.QLineEdit(Form)
        self.nrm_lineEdit.setGeometry(QtCore.QRect(180, 130, 351, 31))
        self.nrm_lineEdit.setObjectName("nrm_lineEdit")
        self.rgh_lineEdit = QtWidgets.QLineEdit(Form)
        self.rgh_lineEdit.setGeometry(QtCore.QRect(180, 170, 351, 31))
        self.rgh_lineEdit.setObjectName("rgh_lineEdit")
        self.met_lineEdit = QtWidgets.QLineEdit(Form)
        self.met_lineEdit.setGeometry(QtCore.QRect(180, 210, 351, 31))
        self.met_lineEdit.setObjectName("met_lineEdit")
        self.bmp_lineEdit = QtWidgets.QLineEdit(Form)
        self.bmp_lineEdit.setGeometry(QtCore.QRect(180, 290, 351, 31))
        self.bmp_lineEdit.setObjectName("bmp_lineEdit")
        self.emi_lineEdit = QtWidgets.QLineEdit(Form)
        self.emi_lineEdit.setGeometry(QtCore.QRect(180, 330, 351, 31))
        self.emi_lineEdit.setObjectName("emi_lineEdit")
        self.col_toolButton = QtWidgets.QToolButton(Form)
        self.col_toolButton.setGeometry(QtCore.QRect(550, 90, 31, 31))
        self.col_toolButton.setObjectName("col_toolButton")
        self.nrm_toolButton = QtWidgets.QToolButton(Form)
        self.nrm_toolButton.setGeometry(QtCore.QRect(550, 130, 31, 31))
        self.nrm_toolButton.setObjectName("nrm_toolButton")
        self.rgh_toolButton = QtWidgets.QToolButton(Form)
        self.rgh_toolButton.setGeometry(QtCore.QRect(550, 170, 31, 31))
        self.rgh_toolButton.setObjectName("rgh_toolButton")
        self.met_toolButton = QtWidgets.QToolButton(Form)
        self.met_toolButton.setGeometry(QtCore.QRect(550, 210, 31, 31))
        self.met_toolButton.setObjectName("met_toolButton")
        self.ao_toolButton = QtWidgets.QToolButton(Form)
        self.ao_toolButton.setGeometry(QtCore.QRect(550, 250, 31, 31))
        self.ao_toolButton.setObjectName("ao_toolButton")
        self.bmp_toolButton = QtWidgets.QToolButton(Form)
        self.bmp_toolButton.setGeometry(QtCore.QRect(550, 290, 31, 31))
        self.bmp_toolButton.setObjectName("bmp_toolButton")
        self.emi_toolButton = QtWidgets.QToolButton(Form)
        self.emi_toolButton.setGeometry(QtCore.QRect(550, 330, 31, 31))
        self.emi_toolButton.setObjectName("emi_toolButton")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(390, 390, 88, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 390, 88, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.select_multiple_image.clicked.connect(self.open_fileDialog_select_multiple_image)
        self.col_toolButton.clicked.connect(self.open_fileDialog_select_col)
        self.nrm_toolButton.clicked.connect(self.open_fileDialog_select_nrm)
        self.rgh_toolButton.clicked.connect(self.open_fileDialog_select_rgh)
        self.rgh_toolButton.clicked.connect(self.open_fileDialog_select_met)
        self.ao_toolButton.clicked.connect(self.open_fileDialog_select_ao)
        self.bmp_toolButton.clicked.connect(self.open_fileDialog_select_bmp)
        self.emi_toolButton.clicked.connect(self.open_fileDialog_select_emi)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Katana Workflow to Image Maps"))
        self.select_multiple_image.setText(_translate("Form", "Select Multiple Image"))
        self.col_label.setText(_translate("Form", "Color"))
        self.nrm_label.setText(_translate("Form", "Normal"))
        self.rgh_label.setText(_translate("Form", "Roughness"))
        self.met_label.setText(_translate("Form", "Metalness"))
        self.ao_label.setText(_translate("Form", "Ambient Occlusion"))
        self.emi_label.setText(_translate("Form", "Emission"))
        self.bmp_label.setText(_translate("Form", "Height"))
        self.col_toolButton.setText(_translate("Form", "..."))
        self.nrm_toolButton.setText(_translate("Form", "..."))
        self.rgh_toolButton.setText(_translate("Form", "..."))
        self.met_toolButton.setText(_translate("Form", "..."))
        self.ao_toolButton.setText(_translate("Form", "..."))
        self.bmp_toolButton.setText(_translate("Form", "..."))
        self.emi_toolButton.setText(_translate("Form", "..."))
        self.pushButton.setText(_translate("Form", "Apply"))
        self.pushButton_2.setText(_translate("Form", "Cancel"))

    def open_fileDialog_select_multiple_image(self):
        options = QFileDialog.Options()
        file_dialog = QFileDialog()
        file_dialog.setWindowTitle("Katana Workflow to Image Maps")
        file_dialog.setDirectory(home)
        file_dialog.setNameFilter("Image files (*.jpg *.png *.bmp *.jpeg *.tif)")
        file_paths, _ = file_dialog.getOpenFileNames(None, "Open Images", "", "Image files (*.jpg *.png *.bmp *.jpeg *.tif)", options=options)

        if file_paths:
            # Do something with the selected file paths, e.g., display them in a text field or store them in a variable.
            # Here, I'm just printing the selected file paths to the console.
            print("Selected image files:")
            for path in file_paths:
                print(path)

    def open_fileDialog_select_col(self):
        options = QFileDialog.Options()
        file_dialog = QFileDialog()
        file_dialog.setWindowTitle("Base Color")
        file_dialog.setDirectory(home)
        file_dialog.setNameFilter("Image files (*.jpg *.png *.bmp *.jpeg *.tif)")
        file_paths, _ = file_dialog.getOpenFileNames(None, "Open Images", "", "Image files (*.jpg *.png *.bmp *.jpeg *.tif)", options=options)

        if file_paths:
            selected_file = file_paths[0]
            self.col_lineEdit.setReadOnly(True)
            self.col_lineEdit.setText(selected_file)

    def open_fileDialog_select_nrm(self):
        options = QFileDialog.Options()
        file_dialog = QFileDialog()
        file_dialog.setWindowTitle("Normal")
        file_dialog.setDirectory(home)
        file_dialog.setNameFilter("Image files (*.jpg *.png *.bmp *.jpeg *.tif)")
        file_paths, _ = file_dialog.getOpenFileNames(None, "Open Images", "", "Image files (*.jpg *.png *.bmp *.jpeg *.tif)", options=options)

        if file_paths:
            selected_file = file_paths[0]
            self.col_lineEdit.setReadOnly(True)
            self.nrm_lineEdit.setText(selected_file)

    def open_fileDialog_select_rgh(self):
        options = QFileDialog.Options()
        file_dialog = QFileDialog()
        file_dialog.setWindowTitle("Roughness")
        file_dialog.setDirectory(home)
        file_dialog.setNameFilter("Image files (*.jpg *.png *.bmp *.jpeg *.tif)")
        file_paths, _ = file_dialog.getOpenFileNames(None, "Open Images", "", "Image files (*.jpg *.png *.bmp *.jpeg *.tif)", options=options)

        if file_paths:
            selected_file = file_paths[0]
            self.col_lineEdit.setReadOnly(True)
            self.rgh_lineEdit.setText(selected_file)

    def open_fileDialog_select_met(self):
        options = QFileDialog.Options()
        file_dialog = QFileDialog()
        file_dialog.setWindowTitle("Metalness")
        file_dialog.setDirectory(home)
        file_dialog.setNameFilter("Image files (*.jpg *.png *.bmp *.jpeg *.tif)")
        file_paths, _ = file_dialog.getOpenFileNames(None, "Open Images", "", "Image files (*.jpg *.png *.bmp *.jpeg *.tif)", options=options)

        if file_paths:
            selected_file = file_paths[0]
            self.col_lineEdit.setReadOnly(True)
            self.met_lineEdit.setText(selected_file)

    def open_fileDialog_select_ao(self):
        options = QFileDialog.Options()
        file_dialog = QFileDialog()
        file_dialog.setWindowTitle("Ambient occlusion")
        file_dialog.setDirectory(home)
        file_dialog.setNameFilter("Image files (*.jpg *.png *.bmp *.jpeg *.tif)")
        file_paths, _ = file_dialog.getOpenFileNames(None, "Open Images", "", "Image files (*.jpg *.png *.bmp *.jpeg *.tif)", options=options)

        if file_paths:
            selected_file = file_paths[0]
            self.col_lineEdit.setReadOnly(True)
            self.ao_lineEdit.setText(selected_file)

    def open_fileDialog_select_bmp(self):
        options = QFileDialog.Options()
        file_dialog = QFileDialog()
        file_dialog.setWindowTitle("Height")
        file_dialog.setDirectory(home)
        file_dialog.setNameFilter("Image files (*.jpg *.png *.bmp *.jpeg *.tif)")
        file_paths, _ = file_dialog.getOpenFileNames(None, "Open Images", "", "Image files (*.jpg *.png *.bmp *.jpeg *.tif)", options=options)

        if file_paths:
            selected_file = file_paths[0]
            self.col_lineEdit.setReadOnly(True)
            self.bmp_lineEdit.setText(selected_file)


    def open_fileDialog_select_emi(self):
        options = QFileDialog.Options()
        file_dialog = QFileDialog()
        file_dialog.setWindowTitle("Emission")
        file_dialog.setDirectory(home)
        file_dialog.setNameFilter("Image files (*.jpg *.png *.bmp *.jpeg *.tif)")
        file_paths, _ = file_dialog.getOpenFileNames(None, "Open Images", "", "Image files (*.jpg *.png *.bmp *.jpeg *.tif)", options=options)

        if file_paths:
            selected_file = file_paths[0]
            self.col_lineEdit.setReadOnly(True)
            self.emi_lineEdit.setText(selected_file)


# Build UI
    app = QtWidgets.QApplication.instance()
    Form = QtWidgets.QWidget()
    ui = MainUI()
    ui.setupUi(Form)
    Form.show()